### ISSUE TITLE
Merge a silence and side bar, it becomes sidebar or silence, whichever is last.

### ISSUE THREAD

**Issue by rachanasinghg** [daisy/obi#165]
Merge a silence and side bar, it becomes sidebar or silence, whichever is last.

**Comment by avneeshsingh** [comment]
moved to next milestone

**Comment by avneeshsingh** [comment]
Moved to next milestone.

**Comment by avneeshsingh** [comment]
Silence phrase is special phrase created for picking up parameters for phrase detection, while sidebar is a phrase with audio. Therefore if a silence phrase is merged with sidebar, silence role should be removed and it should have role of sidebar.
