### ISSUE TITLE
Import EPUB 3 creates improper structure of the project, if the EPUB 3 books do not have IDs in headings and pages

### ISSUE THREAD

**Issue by rachanasinghg** [daisy/obi#168]
For text only EPUB 3 books, Import EPUB 3 command creates improper structure in the project, if the EPUB 3 books do not have IDs in headings and pages

**Comment by avneeshsingh** [comment]
Moved to next milestone

**Comment by avneeshsingh** [comment]
DAISY export is the primary export used, EPUB 3 export usage is quite less as compared to DAISY export.
Therefore allocating resources to fix this EPUB 3 specific issue does not provide a good benefit to cost ratio.
