### ISSUE TITLE
Importing audio files from a subdirectory placed inside the project directory result in moving files instead of copying

### ISSUE THREAD

**Issue by rachanasinghg** [daisy/obi#169]
Steps:

- Copy paste data directory in the same project
- Import audio files from the copied data directory

Result: Files from copied data directory will be removed and added to data directory (after renaming). Instead of removing files, Obi should copy them. The behavior is correct if files are imported from a directory that lie outside the project directory.

**Comment by avneeshsingh** [comment]
moved to next milestone

**Comment by avneeshsingh** [comment]
Moved to next milestone

**Comment by avneeshsingh** [comment]
Moved to next release

**Comment by avneeshsingh** [comment]
A warning message is provided to alert user, if files are being imported from within the project directory.
