### ISSUE TITLE
Show all TOC in preview

### ISSUE THREAD

**Issue by yuzawijaksana** [daisy/obi#225]
![image](https://github.com/daisy/obi/assets/48989307/26963d4a-b3b3-4c0d-b829-bf4c2dab1811)

how do i do this in the newer version (4.8) ?

ive seen this on youtube that was uploaded on the year 2010.  i still dont know how to do it. ive searched everywhere and still not find it.

**Comment by yuzawijaksana** [comment]
My current version just shows one section and not all section 
![image](https://github.com/daisy/obi/assets/48989307/fb654c82-c573-4209-b7e5-bc8eb927b899)

**Comment by rachanasinghg** [comment]
Hello Yuja,
Thank you for writing to us.
We have removed this feature of showing multiple Sections in Content View.
Currently you can only view 1 section in Content View and need to scroll down (Keys CTRL + SHIFT + Down Arrow) to view other sections.

With Regards
Rachana
Obi Team

**Comment by yuzawijaksana** [comment]
Is there any way that i can show all ? i need it for easier use

**Comment by avneeshsingh** [comment]
We had to disable this feature due to serious performance issues. Reading multiple wav files in a large project and then displaying it on screen takes CPU cycles and time. We made this decision more than 10 years ago based on feedback from production studio users.

**Comment by avneeshsingh** [comment]
That version of Obi was on .NET 2.0, and was using old technologies. It may not work properly with latest technologies. Therefore we will not recommend use of such an old version.

**Comment by avneeshsingh** [comment]
Feature removed from Obi due to performance related issues.
